# Generated by Django 2.2.2 on 2020-03-19 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('passagem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemarcacaoPassagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_viagem', models.DateTimeField()),
                ('valor', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('multa', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('tarifa', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('passagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='passagem.Passagem')),
            ],
            options={
                'verbose_name': 'Remarcacao',
                'verbose_name_plural': 'Remarcacaoß',
                'ordering': ('data_viagem',),
            },
        ),
    ]
