# Generated by Django 2.2.2 on 2020-03-27 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passagem', '0004_remarcacaopassagem_data_remarcacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='passageiro',
            name='fone',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='passageiro',
            name='servidor',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='passageiro',
            name='tipo',
            field=models.CharField(choices=[('is_crianca_1', 'Criança de 0 a 2 anos'), ('is_crianca_2', 'Criança de 2 a 12 anos'), ('is_crianca_2', 'Pessoa acima de 12 anos')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
