# Generated by Django 2.2.2 on 2020-03-27 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passagem', '0005_auto_20200327_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='passageiro',
            name='email',
            field=models.EmailField(db_index=True, default=1, max_length=255, unique=True, verbose_name='Endereço de Email'),
            preserve_default=False,
        ),
    ]
