# Generated by Django 2.2.2 on 2020-03-27 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passagem', '0006_passageiro_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passageiro',
            old_name='tipo',
            new_name='categoria',
        ),
    ]
