# Generated by Django 2.2.2 on 2020-03-30 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passagem', '0007_auto_20200327_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passageiro',
            name='categoria',
            field=models.CharField(choices=[('is_crianca_1', 'Criança de 0 a 2 anos'), ('is_crianca_2', 'Criança de 2 a 12 anos'), ('is_adulto', 'Pessoa acima de 12 anos')], max_length=100),
        ),
        migrations.AlterField(
            model_name='passageiro',
            name='data_nascimento',
            field=models.DateField(),
        ),
    ]
