# Generated by Django 2.2.2 on 2020-04-01 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passagem', '0008_auto_20200330_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaopassagem',
            name='justificativa_urgencia',
            field=models.TextField(blank=True, null=True, verbose_name='Justificativa da Urgência'),
        ),
        migrations.AddField(
            model_name='solicitacaopassagem',
            name='urgente',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
