# Generated by Django 2.2.2 on 2020-04-06 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passagem', '0009_auto_20200401_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='passageiropassagem',
            name='data_viagem',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
