# Generated by Django 2.2.2 on 2019-09-19 16:56

import auth_local.models.usuario_orgao
from django.db import migrations, models
import django.db.models.deletion
import util.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('basico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Perfil')),
            ],
            options={
                'db_table': 'auth_local_perfil',
                'default_related_name': 'perfil',
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(max_length=500, verbose_name='Hash')),
                ('data_expiracao', models.DateTimeField(verbose_name='Data de Expiração')),
                ('is_usado', models.BooleanField(default=False, verbose_name='Usado?')),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioOrgao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('cpf', models.CharField(max_length=14, verbose_name='CPF do Usuário')),
                ('nome', util.fields.CharUpperField(max_length=100, verbose_name='Nome')),
                ('email', models.EmailField(db_index=True, max_length=255, unique=True, verbose_name='Endereço de Email')),
                ('foto', models.ImageField(blank=True, null=True, upload_to=auth_local.models.usuario_orgao.name_foto_perfil_usuario, verbose_name='Foto de Perfil')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('is_first_login', models.BooleanField(default=False, verbose_name='Primeiro Login?')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('orgao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuario_orgao', to='basico.Orgao', verbose_name='Órgão')),
                ('perfil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuario_perfil', to='auth_local.Perfil', verbose_name='Perfil')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'auth_local_usuario_orgao',
                'default_related_name': 'usuario_orgao',
            },
        ),
    ]
