# Generated by Django 2.2.2 on 2019-09-19 16:56

from django.db import migrations, models
import django.db.models.deletion
import util.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orgao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', util.fields.CharUpperField(max_length=100, verbose_name='Razão Social')),
                ('sigla', util.fields.CharUpperField(blank=True, max_length=25, null=True, verbose_name='Sigla')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Órgão',
                'verbose_name_plural': 'Órgãos',
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', util.fields.CharUpperField(max_length=350, verbose_name='Nome:')),
                ('sigla', util.fields.CharUpperField(max_length=2, verbose_name='Sígla')),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', util.fields.CharUpperField(max_length=350, verbose_name='Nome:')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basico.Pais')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
    ]
